export const AXIOS_TIMEOUT = 10000

const FIVE_MINUTES = 1000 * 60 * 5
export const REACT_QUERY_STALE_TIME = FIVE_MINUTES
// REACT_QUERY_STALE_TIME + 5 minutes
export const REACT_QUERY_CACHE_TIME = REACT_QUERY_STALE_TIME + FIVE_MINUTES
